# Generated by Django 5.0.7 on 2024-07-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('ciudad_nacimiento', models.CharField(blank=True, max_length=100)),
                ('provincia_nacimiento', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.CharField(max_length=150, unique=True)),
                ('contrasenia', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
